http:
- matchers:
  - condition: and
    part: body
    type: word
    words:
    - 'version:'
    - 'os:'
    - 'files:'
  - status:
    - 200
    type: status
  matchers-condition: and
  method: GET
  path:
  - '{{BaseURL}}/appspec.yml'
  - '{{BaseURL}}/appspec.yaml'
  - '{{BaseURL}}/%2e/appspec.yml'
  - '{{BaseURL}}/%2e/appspec.yaml'
  - '{{BaseURL}}/;/appspec.yml'
  - '{{BaseURL}}/;/appspec.yaml'
  - '{{BaseURL}}/..;/appspec.yml'
  - '{{BaseURL}}/..;/appspec.yaml'
  - '{{BaseURL}}/%2e%2e%2f/appspec.yml'
  - '{{BaseURL}}/%2e%2e%2f/appspec.yaml'
  - '{{BaseURL}}/..%3B/appspec.yml'
  - '{{BaseURL}}/..%3B/appspec.yaml'
  stop-at-first-match: true
id: appspec-yml-disclosure
info:
  author: dhiyaneshDk,reewardius
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:N/A:N
    cvss-score: 5.3
    cwe-id: CWE-200
  description: Appspec YML and YAML files are susceptible to information disclosure.
  name: Appspec YML/YAML - Detect
  reference:
  - https://github.com/detectify/ugly-duckling/blob/master/modules/crowdsourced/appsec-yml-disclosure.json
  severity: medium
  tags: java,generic
