http:
- matchers:
  - case-insensitive: true
    condition: and
    type: word
    words:
    - ssh_authorized_keys
    - '#cloud-config'
  - status:
    - 200
    type: status
  matchers-condition: and
  method: GET
  path:
  - '{{BaseURL}}/cloud-config.yml'
  - '{{BaseURL}}/core-cloud-config.yml'
  - '{{BaseURL}}/cloud-config.yaml'
  - '{{BaseURL}}/core-cloud-config.yaml'
  - '{{BaseURL}}/cloud-config.yml.old'
  - '{{BaseURL}}/core-cloud-config.yml.old'
  - '{{BaseURL}}/cloud-config.yaml.old'
  - '{{BaseURL}}/core-cloud-config.yaml.old'
  - '{{BaseURL}}/cloud-config.txt'
  stop-at-first-match: true
id: cloud-config
info:
  author: DhiyaneshDK,Hardik-Solanki
  metadata:
    shodan-query: html:"cloud-config.yml"
    verified: true
  name: Cloud Config File Exposure
  reference: https://www.exploit-db.com/ghdb/7959
  severity: medium
  tags: generic,config
