http:
- matchers:
  - dsl:
    - 'regex("^version: ", body) && contains(body, "services:")'
    type: dsl
  - status:
    - 200
    type: status
  matchers-condition: and
  method: GET
  path:
  - '{{BaseURL}}/docker-compose.yml'
  - '{{BaseURL}}/docker-compose.prod.yml'
  - '{{BaseURL}}/docker-compose.production.yml'
  - '{{BaseURL}}/docker-compose.staging.yml'
  - '{{BaseURL}}/docker-compose.dev.yml'
  - '{{BaseURL}}/docker-compose-dev.yml'
  - '{{BaseURL}}/docker-compose.override.yml'
  stop-at-first-match: true
id: docker-compose-config
info:
  author: meme-lord,blckraven,geeknik
  name: docker-compose.yml exposure
  severity: medium
  tags: generic,docker
