id: dockerfile-hidden-disclosure
info:
  author: dhiyaneshDk
  name: Dockerfile Hidden Disclosure
  reference: https://github.com/detectify/ugly-duckling/blob/master/modules/crowdsourced/dockerfile-hidden-disclosure.json
  severity: medium
  tags: exposure,config
requests:
- matchers:
  - part: body
    regex:
    - ^(?:FROM(?:CACHE)?|RUN|ADD|WORKDIR|ENV|EXPOSE|\#)\s+[ -~]+
    type: regex
  - status:
    - 200
    type: status
  - negative: true
    part: header
    type: word
    words:
    - text/html
  matchers-condition: and
  method: GET
  path:
  - '{{BaseURL}}/.dockerfile'
  - '{{BaseURL}}/.Dockerfile'
