http:
- matchers:
  - part: body
    regex:
    - ^(?:FROM(?:CACHE)?|RUN|ADD|WORKDIR|ENV|EXPOSE|\#)\s+[ -~]+
    type: regex
  - status:
    - 200
    type: status
  - negative: true
    part: header
    type: word
    words:
    - text/html
  matchers-condition: and
  method: GET
  path:
  - '{{BaseURL}}/.dockerfile'
  - '{{BaseURL}}/.Dockerfile'
  - '{{BaseURL}}/Dockerfile'
id: dockerfile-hidden-disclosure
info:
  author: dhiyaneshDk
  classification:
    cvss-metrics: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:N/A:N
    cvss-score: 5.3
    cwe-id: CWE-200
  description: Dockerfile was detected.
  metadata:
    max-request: 3
  name: Dockerfile - Detect
  reference:
  - https://github.com/detectify/ugly-duckling/blob/master/modules/crowdsourced/dockerfile-hidden-disclosure.json
  severity: medium
  tags: exposure,config,vuln
