http:
- matchers:
  - case-insensitive: true
    condition: and
    part: body
    type: word
    words:
    - OVPN Config Download
    - Config List
  - status:
    - 200
    type: status
  matchers-condition: and
  method: GET
  path:
  - '{{BaseURL}}'
id: ovpn-config-exposed
info:
  author: tess
  metadata:
    max-request: 1
  name: OVPN Config Download
  severity: low
  tags: config,exposed,generic
