http:
- matchers:
  - part: body
    type: word
    words:
    - /usr/bin/env php
  - status:
    - 200
    type: status
  matchers-condition: and
  method: GET
  path:
  - '{{BaseURL}}/composer'
id: php-composer-binary
info:
  author: mayank_pandey01
  description: 'This Nuclei template checks if the specified endpoints have Publically
    Accessible PHP Composer Binary.

    '
  name: Publically Accessible PHP Composer Binary
  remediation: 'Restrict access to the PHP Composer binary by implementing proper
    access controls and permissions.

    '
  severity: info
  tags: php,composer,generic
