id: proftpd-config
info:
  author: sheikhrishad
  name: ProFTPD Config file disclosure
  severity: low
  tags: config,exposure,proftpd
requests:
- attack: sniper
  matchers:
  - condition: and
    type: word
    words:
    - ProFTPD
    - ServerName
  - status:
    - 200
    type: status
  matchers-condition: and
  payloads:
    Subdomains: /home/mahmoud/Wordlist/AllSubdomains.txt
  raw:
  - 'GET /proftpd.conf HTTP/1.1

    Host: {{Subdomains}}

    User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:55.0) Gecko/20100101
    Firefox/55

    '
  threads: 100
