http:
- matchers:
  - condition: or
    type: word
    words:
    - gateway_request_total
    - logback_events_total
  - status:
    - 200
    type: status
  matchers-condition: and
  method: GET
  path:
  - '{{BaseURL}}/prometheus'
  - '{{BaseURL}}/actuator/prometheus'
id: prometheus-log
info:
  author: dhiyaneshDK
  metadata:
    max-request: 2
  name: Exposed Prometheus
  severity: low
  tags: prometheus
