http:
- matchers:
  - condition: and
    part: body
    type: word
    words:
    - run Rails.application
    - /config/environment
  - condition: and
    part: body
    type: word
    words:
    - Bundler.require
    - require 'rubygems'
  matchers-condition: or
  method: GET
  path:
  - '{{BaseURL}}/config.ru'
id: rackup-config-ru
info:
  author: DhiyaneshDk
  metadata:
    max-request: 1
  name: Rackup config.ru Configuration Exposure
  reference:
  - https://raw.githubusercontent.com/maurosoria/dirsearch/master/db/dicc.txt
  - https://learn.co/lessons/config-ru-tutorial
  severity: info
  tags: config-files,config
