http:
- matchers:
  - case-insensitive: true
    condition: and
    part: body
    type: word
    words:
    - 'build:'
    - 'filter:'
    - 'tools:'
  - status:
    - 200
    type: status
  matchers-condition: and
  method: GET
  path:
  - '{{BaseURL}}/.scrutinizer.yml'
  - '{{BaseURL}}/scrutinizer.yml'
id: scrutinizer-config
info:
  author: DhiyaneshDK
  metadata:
    max-request: 2
  name: Scrutinizer Config File Exposure
  severity: info
  tags: config-files,config
