http:
- matchers:
  - condition: and
    part: body
    type: word
    words:
    - '[DEFAULT]'
    - test_path=
  - status:
    - 200
    type: status
  matchers-condition: and
  method: GET
  path:
  - '{{BaseURL}}/.stestr.conf'
  - '{{BaseURL}}/stestr.conf'
id: stestr-config
info:
  author: Hardik-Solanki
  metadata:
    max-request: 2
  name: Stestr Configuration File Exposure
  severity: info
  tags: config-files,config
