http:
- matchers:
  - condition: and
    type: word
    words:
    - '[Server]'
    - Name
    - Phonetic
  - condition: or
    part: header
    type: word
    words:
    - text/plain
    - bytes
  - negative: true
    part: header
    type: word
    words:
    - text/html
  - condition: or
    status:
    - 200
    - 206
    type: status
  matchers-condition: and
  method: GET
  path:
  - '{{BaseURL}}/ventrilo_srv.ini'
  - '{{BaseURL}}/.ventrilo_srv.ini'
id: ventrilo-config
info:
  author: geeknik
  metadata:
    max-request: 2
  name: Ventrilo Configuration File
  severity: high
  tags: generic,config
